language: java
addons:
  firefox: "56.0b12"
  apt:
    packages:
      - xvfb
sudo: false
before_install:
  - sudo apt-get install dbus dbus-x11 
 # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./.travis-publishOnRelease.sh
